/**
 * Extraction entry point. Writes the card data, the fabrication candidates, and
 * a human-readable report whose counts are computed rather than asserted.
 *
 * Run with: npm run extract --workspace @hot-seat/corpus
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { buildCorpus } from './normalize.js'
import { findFabricationCandidates } from './fabrications.js'
import { SOURCES } from './sources.js'

const DATA_DIR = new URL('../data/', import.meta.url)
const out = (name) => fileURLToPath(new URL(name, DATA_DIR))

const pct = (n, total) => (total === 0 ? '0' : ((n / total) * 100).toFixed(0))

const renderReport = ({ cards, narrative, counts, duplicates }, candidates) => {
  const familyRows = Object.entries(counts.by_family)
    .map(([family, n]) => `| ${family} | ${n} |`)
    .join('\n')

  const dupRows = duplicates
    .map((d) => `| \`${d.slug}\` | ${d.title} | ${[...new Set(d.families)].join(' + ')} |`)
    .join('\n')

  const incomplete = cards.filter((c) => c.missing_facets.length > 0)
  const incompleteRows = incomplete
    .map((c) => `| \`${c.slug}\` | ${c.missing_facets.join(', ')} |`)
    .join('\n')

  const absent = cards.filter((c) => c.facets.benchmark.state === 'absent')

  const promptCounts = cards
    .concat(narrative)
    .flatMap((c) => c.supported_prompt_types)
    .reduce((acc, t) => ({ ...acc, [t]: (acc[t] ?? 0) + 1 }), {})

  return `# Corpus extraction report

Generated by \`packages/corpus/src/extract.js\`. Every number here is counted
from the research files at run time. Nothing is transcribed, so a figure that
looks wrong means the extraction is wrong rather than the note being stale.

## Reconciliation

| | Count |
|---|---|
| Numbered metric sections parsed | ${counts.parsed_metric_sections} |
| Cross-family duplicates merged | ${counts.duplicates_merged} |
| **Metric cards emitted** | **${counts.cards_after_merge}** |
| Narrative entries (essays and prose supplements) | ${counts.parsed_narrative_sections} |

${counts.parsed_metric_sections} sections minus ${counts.duplicates_merged} merges gives ${counts.cards_after_merge} cards.

## Cards by family

| Family | Sections parsed |
|---|---|
${familyRows}

## Benchmarks

| State | Cards | Share |
|---|---|---|
| Present, with sourced rows | ${counts.benchmark_present} | ${pct(counts.benchmark_present, cards.length)}% |
| Absent, no primary publisher found | ${counts.benchmark_absent} | ${pct(counts.benchmark_absent, cards.length)}% |

An absent benchmark is a result, not a gap. The corpus records that it looked
and found nothing sourced, which is what lets a card answer "nobody publishes
this" instead of repeating an unsourced figure.

### Verification tier

Three tag vocabularies appear across the corpus and are mapped onto one enum:
\`[P]/[S]/[W]\`, \`[V]/[V-2nd]/[S]/[NONE]\`, and a variant where \`[S]\` means a
credible aggregator citing a named primary.

The tags annotate individual claims, usually on bullets in the prose rather than
in benchmark table cells, so a card's tier is the strongest tag anywhere in its
section. Untagged stays untagged: inferring a tier from how respectable a source
looks would manufacture the false confidence this corpus exists to argue against.

| Strongest tag in the section | Cards |
|---|---|
${Object.entries(counts.by_tier)
  .sort((a, b) => b[1] - a[1])
  .map(([tier, n]) => `| ${tier} | ${n} |`)
  .join('\n')}

Across ${counts.benchmark_rows} individual benchmark rows.

${absent.length > 0 ? `<details>\n<summary>${absent.length} cards with no sourced benchmark</summary>\n\n${absent.map((c) => `- \`${c.slug}\` ${c.title}`).join('\n')}\n\n</details>` : ''}

## Merged duplicates

The same metric appearing in more than one family collapses to a single card
reachable from either. The richer entry supplies the facets.

| Slug | Title | Families |
|---|---|---|
${dupRows}

## Incomplete cards

${
  incomplete.length === 0
    ? 'None. Every card carries every facet the corpus defines for it.'
    : `${incomplete.length} cards are missing at least one facet other than benchmark. These are reported rather than silently emitted as partial cards.\n\n| Slug | Missing |\n|---|---|\n${incompleteRows}`
}

## Prompt inventory

How many cards can support each question type. A type is only offered when the
facet behind it actually carries content, which is what stops the interrogator
asking something the corpus cannot answer.

| Prompt type | Cards |
|---|---|
${Object.entries(promptCounts)
  .sort((a, b) => b[1] - a[1])
  .map(([type, n]) => `| ${type} | ${n} |`)
  .join('\n')}

Distinct single-facet questions available: **${Object.values(promptCounts).reduce((a, b) => a + b, 0)}**.

## Fabrication candidates

Passages in the research that discuss a fabricated or misattributed benchmark.
**These are candidates for review, not the fabrication catalogue.** The corpus
flags fabrications in prose rather than with a structured marker, and an entry
in the real catalogue asserts that a named publisher did not publish something,
which is too consequential to derive from a keyword match.

${candidates.length} passages found across ${new Set(candidates.map((c) => c.file)).size} files. The
curated catalogue lives in \`fabrications.json\` and is seeded from this list by
hand.

${candidates.map((c) => `- **${c.file}** line ${c.line}: ${c.excerpt}`).join('\n')}

## Source files

| File | Family | Metric heading level |
|---|---|---|
${SOURCES.map((s) => `| ${s.file} | ${s.family} | ${s.supplement ? 'prose supplement' : `h${s.metricLevel}`} |`).join('\n')}
`
}

export const run = () => {
  const corpus = buildCorpus()
  const candidates = findFabricationCandidates()

  mkdirSync(fileURLToPath(DATA_DIR), { recursive: true })

  writeFileSync(
    out('cards.json'),
    `${JSON.stringify(
      {
        generated_from: 'packages/corpus/research',
        card_count: corpus.cards.length,
        narrative_count: corpus.narrative.length,
        cards: corpus.cards,
        narrative: corpus.narrative
      },
      null,
      2
    )}\n`
  )

  writeFileSync(
    out('fabrication-candidates.json'),
    `${JSON.stringify({ candidate_count: candidates.length, candidates }, null, 2)}\n`
  )

  writeFileSync(out('extraction-report.md'), renderReport(corpus, candidates))

  return { ...corpus.counts, fabrication_candidates: candidates.length }
}

// Only run when invoked directly, so tests can import without writing files.
if (process.argv[1] && import.meta.url === `file://${process.argv[1]}`) {
  const counts = run()
  console.log('Extraction complete.')
  for (const [key, value] of Object.entries(counts)) {
    if (typeof value === 'object') continue
    console.log(`  ${key.padEnd(28)} ${value}`)
  }
}
